#pragma once

/*=================================================================*/
/*  This is generated by the build system. Do not edit this file.  */
/*=================================================================*/

#define PROJECT_NAME "lv2-skeleton"
#define PROJECT_DISPLAY_NAME "LV2 example"
#define PROJECT_URI "urn:jpcima:lv2-example"
