macro(find_static_library)
  set(_orig_CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_FIND_LIBRARY_SUFFIXES}")
  if (WIN32)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".a")
  else()
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
  endif()
  find_library(${ARGN})
  set(CMAKE_FIND_LIBRARY_SUFFIXES "${_orig_CMAKE_FIND_LIBRARY_SUFFIXES}")
  unset(_orig_CMAKE_FIND_LIBRARY_SUFFIXES)
endmacro()
